### ISSUE TITLE
OSError: [Errno 22]  during scvae evaluate

### ISSUE THREAD

**Issue by pchiang5** [scvae/scvae#10]
Hello,

When I tried to use scvae with a loom data, everything was fine during the following step:
'scvae evaluate "xxx.loom" --split-data-set'

However, it showed the following error when I executed 'scvae evaluate "xxx.loom" --split-data-set':

#########################
←[1mReconstructions
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
←[0m
Plotting profile comparisons.
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\scvae.exe\__main__.py", line 7, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\scvae\cli.py", line 1222, in main
    status = arguments.func(**vars(arguments))
  File "c:\programdata\miniconda3\lib\site-packages\scvae\cli.py", line 555, in evaluate
    analyses_directory=analyses_directory
  File "c:\programdata\miniconda3\lib\site-packages\scvae\analyses\analyses.py", line 1155, in analyse_results
    directory=profile_comparisons_directory
  File "c:\programdata\miniconda3\lib\site-packages\scvae\analyses\figures\saving.py", line 92, in save_figure
    figure.savefig(figure_path)
  File "c:\programdata\miniconda3\lib\site-packages\matplotlib\figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\matplotlib\backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "c:\programdata\miniconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\programdata\miniconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "c:\programdata\miniconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 22] Invalid argument: 'analyses\\gas8000\\split-random_0.9\\no_preprocessing\\VAE\\gaussian\\poisson-l_2-h_100-mc_1-iw_1-kl-bn\\e_200-mc_1-iw_1\\profile_comparisons\\profile_comparison-"cell_113865"-linear-sorted.png'
########################

Is there any reason causing the problem?

Thanks
Po

**Comment by chgroenbech** [comment]
This seems to be a problem with filename on Windows. I have a fix for this in the next version.
