### ISSUE TITLE
ValueError: Data format already specified in metadata and cannot be changed (is `gz`; wanted `matrix_fbe`).

### ISSUE THREAD

**Issue by wenyuhaokikika** [scvae/scvae#20]
Hello，thanks for scvae~~~

I encounter a problem

I want to train for TCGA/XENA transcript data, download data from [page xena](https://xenabrowser.net/datapages/?dataset=tcga_expected_count&host=https%3A%2F%2Ftoil.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443)

```sh
alias proxychains='/data/wenyuhao/software/proxychains/bin/proxychains4 -f /data/wenyuhao/software/proxychains/proxychains.conf'
proxychains wget https://toil-xena-hub.s3.us-east-1.amazonaws.com/download/tcga_expected_count.gz
```

`tcga_expected_count.gz` is TSV file(gzip compressed) with transcript as rows and samples as columns,so I use `--format matrix_fbe`

```sh
└─(16:36:15 on master ✭)──> zcat tcga_expected_count.gz | head -10 | csvcut -t -c 1-10 | csvformat -T                                      ──(Tue,Oct03)─┘
sample  TCGA-S9-A7J2-01 TCGA-G3-A3CH-11 TCGA-EK-A2RE-01 TCGA-D5-5538-01 TCGA-IQ-A61O-01 TCGA-AB-2863-03 TCGA-G9-6499-11 TCGA-C8-A1HL-01 TCGA-EW-A2FS-01
ENST00000548312.5       1.8074  1.4906  1.6781  1.8914  3.2388  3.2126  2.7929  0.0000  0.0000
ENST00000483781.5       1.2449  0.0000  1.5850  0.0000  0.0000  2.3074  0.0000  0.0000  0.0000
ENST00000535093.1       0.0000  0.0000  0.0000  0.0000  0.0000  0.0     0.0000  0.0000  0.0000
ENST00000338863.11      8.7317  8.0738  11.9031 10.7103 10.3966 0.0     11.8987 9.0007  9.6170
ENST00000570899.1       0.0000  0.0000  1.7698  0.0000  2.5236  0.0     1.7268  2.0179  0.0000
ENST00000556831.5       4.2979  1.7485  2.8953  1.1763  1.1827  4.0009  0.0000  4.8006  3.8490
ENST00000625998.2       9.4804  0.0000  7.6738  8.2678  7.7274  7.4629  11.2444 0.6041  10.0544
ENST00000583693.5       8.9606  5.0670  5.7057  5.6453  5.3402  6.7979  5.7063  4.7777  7.3460
ENST00000580812.1       3.7398  0.0000  4.9026  3.9345  2.2510  2.1667  3.4060  0.0000  2.8032
```

![image](https://github.com/scvae/scvae/assets/40107519/d91a599b-f850-4c1e-a51c-43eb54e744d8)

but It raise Exception
```
└─(16:13:17 on master ✭)──> scvae train tcga_expected_count.gz -H 1000 500 -l 256 -e 500 -w 200 --learning-rate 0.001 --split-data-set --splitting-fraction 0.9  --format matrix_fbe
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Data
════

Traceback (most recent call last):
  File "/data/wenyuhao/anaconda3/envs/scvae/bin/scvae", line 8, in <module>
    sys.exit(main())
  File "/data/wenyuhao/anaconda3/envs/scvae/lib/python3.7/site-packages/scvae/cli.py", line 1230, in main
    status = arguments.func(**vars(arguments))
  File "/data/wenyuhao/anaconda3/envs/scvae/lib/python3.7/site-packages/scvae/cli.py", line 161, in train
    noisy_preprocessing_methods=noisy_preprocessing_methods
  File "/data/wenyuhao/anaconda3/envs/scvae/lib/python3.7/site-packages/scvae/data/data_set.py", line 187, in __init__
    data_format
ValueError: Data format already specified in metadata and cannot be changed (is `gz`; wanted `matrix_fbe`).
```

when I use without `format`,it also raise Exception
```
└─(16:32:21 on master ✭)──> scvae train tcga_expected_count.gz -H 1000 500 -l 256 -e 500 -w 200 --learning-rate 0.001 --split-data-set --splitting-fraction 0.9                     
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Data
════

Data set:
    title: tcga_expected_count
    feature selection: none
    example filter: none
    processing methods: none

Splitting:
    method: random
    fraction: 90.0 %

Copying values for full set.
Data set copied (2.3 s).

Loading original data set.
Traceback (most recent call last):
  File "/data/wenyuhao/anaconda3/envs/scvae/bin/scvae", line 8, in <module>
    sys.exit(main())
  File "/data/wenyuhao/anaconda3/envs/scvae/lib/python3.7/site-packages/scvae/cli.py", line 1230, in main
    status = arguments.func(**vars(arguments))
  File "/data/wenyuhao/anaconda3/envs/scvae/lib/python3.7/site-packages/scvae/cli.py", line 166, in train
    method=splitting_method, fraction=splitting_fraction)
  File "/data/wenyuhao/anaconda3/envs/scvae/lib/python3.7/site-packages/scvae/data/data_set.py", line 1101, in split
    self.load()
  File "/data/wenyuhao/anaconda3/envs/scvae/lib/python3.7/site-packages/scvae/data/data_set.py", line 770, in load
    data_format=self.data_format
  File "/data/wenyuhao/anaconda3/envs/scvae/lib/python3.7/site-packages/scvae/data/loading.py", line 111, in load_original_data_set
    data_format))
ValueError: Data format `gz` not recognised.
```

python/scvae version
```sh
└─(16:13:59 on master ✭)──> scvae --version                                                                                            1 ↵ ──(Tue,Oct03)─┘
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.

└─(16:31:10)──> python --version                                                                                                           ──(Tue,Oct03)─┘
Python 3.7.12
```

Looking forward to your reply, thank you~~~

**Comment by wenyuhaokikika** [comment]
It must be with `tsv.gz` suffix,`mv tcga_expected_count.gz tcga_expected_count.tsv.gz`

**Comment by wenyuhaokikika** [comment]
I think it is a bug,please fix it.

**Comment by wenyuhaokikika** [comment]
I write a gist for running scvae, https://gist.github.com/wenyuhaokikika/ead3ad64dc7e2f249d75a5af8cf512db
